config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tools#index'

  resources :tools do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, except: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tool
  belongs_to :user

  validates :collect_time, presence: true
  validates :return_time, presence: true
end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :bookings

  # photo uploader
  mount_uploader :photo, PhotoUploader
  validates :name, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tools
  has_many :bookings

  # photo uploader
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  protected

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_tool, only: %i[new create]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    redirect_to bookings_path if @booking.nil?
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.tool = @tool
    authorize @booking
    if @booking.save
      flash.notice = "New booking created."
      redirect_to booking_path @booking
    else
      p @booking.errors
      flash.alert = "The information you entered is incomplete."
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      flash.notice = "Booking has been updated."
      redirect_to booking_path @booking
    else
      p @booking.errors
      flash.alert = "The information you entered is incomplete."
      render :edit
    end
  end

  def destroy
    @booking.destroy
    flash.notice = "Booking has been deleted."
    redirect_to bookings_path
  end

  protected

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  rescue ActiveRecord::RecordNotFound
    flash.alert = "We couldn't find that booking."
    redirect_to bookings_path
  rescue Pundit::NotAuthorizedError
    flash.alert = "You are not allowed to do this action."
    redirect_to bookings_path
  end

  def set_tool
    @tool = Tool.find(params[:tool_id])
  rescue ActiveRecord::RecordNotFound
    flash.alert = "We couldn't find that tool."
    redirect_to bookings_path
  end

  def booking_params
    fields = %i[collect_time return_time collected_time returned_time]
    params.require(:booking).permit(fields)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_tool, only: %i[show edit update destroy]

  def index
    @tools = policy_scope(Tool)
  end

  def show
    redirect_to tools_path if @tool.nil?
  end

  def new
    @tool = Tool.new
    authorize @tool
  end

  def create
    @tool = Tool.new(tool_params)
    @tool.user = current_user
    authorize @tool
    if @tool.save
      flash.notice = "New tool created."
      redirect_to tool_path @tool
    else
      p @tool.errors
      flash.alert = "The information you entered is incomplete."
      render :new
    end
  end

  def edit
  end

  def update
    if @tool.update(tool_params)
      flash.notice = "Tool has been updated."
      redirect_to tool_path @tool
    else
      p @tool.errors
      flash.alert = "The information you entered is incomplete."
      render :edit
    end
  end

  def destroy
    @tool.destroy
    flash.notice = "Tool has been deleted."
    redirect_to tools_path
  end

  protected

  def set_tool
    @tool = Tool.find(params[:id])
    authorize @tool
  rescue ActiveRecord::RecordNotFound
    flash.alert = "We couldn't find that tool."
    redirect_to tools_path
  rescue Pundit::NotAuthorizedError
    flash.alert = "You are not allowed to do this action."
    redirect_to tools_path
  end

  def tool_params
    params.require(:tool).permit(:name, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<% if @booking.id.nil? %>
  <% form_for = [@tool, @booking] %>
<% else %>
  <% form_for = @booking %>
<% end %>

<%= simple_form_for form_for do |f| %>
  <%= f.input :collect_time %>
  <%= f.input :return_time %>
  <% unless @booking.id.nil? %>
    <%= f.input :collected_time %>
    <%= f.input :returned_time %>
  <% end %>
  <%= f.button :submit, class: "btn btn-primary rounded" %>
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
  <h1 class="my-4">Edit Booking</h1>
  <%= render 'form' %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="text-center my-4">
    <span class="h1 h1-smaller mr-1">My Bookings</span>
    <%#= link_to new_tool_path do %>
    <!-- <i class="fa fa-plus"></i> -->
    <%# end %>
  </div>
  <div class="bookings-container">
      <% @bookings.each do |booking| %>
        <div>
          <%= link_to booking_path(booking) do %>
          <i class="fa fa-hammer mr-1"></i>
          <%= booking.tool.name.capitalize %> &nbsp;
          <%= booking.collect_time %>
        </div>
      <% end %>
    <%#= render partial: 'components/booking-card', locals: { booking: booking } %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h1 class="my-4">New Booking</h1>
  <%= render 'form' %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="my-4">
    <span class="h1 h1-smaller mr-1">
      Booking for: <%= @booking.tool.name.capitalize %>
    </span>
    <% if policy(@booking).edit? %>
      <%= link_to edit_booking_path(@booking) do %>
        <i class="fas fa-edit mr-1"></i>
      <% end %>
    <% end %>
    <% if policy(@booking).destroy? %>
      <%= link_to booking_path(@booking), method: :delete,
      data: { confirm: "Are you sure you want to delete this booking?" } do %>
        <i class="fas fa-trash mr-1"></i>
      <% end %>
    <% end %>
  </div>

  <div>
    <q><%= @booking.tool.description %></q>
    <div>From: <%= @booking.collect_time %></div>
    <div>To: <%= @booking.return_time %></div>
  </div>
  <div>
    <p>Collected: <%= @booking.collected_time.nil? ? 'Never' : @booking.collected_time %></p>
    <p>Returned: <%= @booking.returned_time.nil? ? 'Never' : @booking.returned_time %></p>
  </div>
  <div>
    <%= link_to bookings_path do %>
      <i class="fas fa-arrow-left mr-1"></i>
      Back to Bookings
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <a href="<%= root_path %>" class="navbar-brand border rounded-lg p-1">NM</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0 ml-auto mr-2">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to "My Tools", tools_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "dropdown-item"%>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/tools/_form.html.erb
<%= simple_form_for @tool do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.button :submit, class: "btn btn-primary rounded" %>
<% end %>

app/views/tools/edit.html.erb
<div class="container">
  <h1 class="my-4">Edit Tool</h1>
  <%= render 'form' %>
</div>

app/views/tools/index.html.erb
<div class="container">
  <div class="text-center my-4">
    <span class="h1 h1-smaller mr-1">All Tools</span>
    <%= link_to new_tool_path do %>
      <i class="fa fa-plus"></i>
    <% end %>
  </div>
  <div class="tools-container">
    <% @tools.each do |tool| %>
      <%= render partial: 'components/tool-card', locals: { tool: tool } %>
    <% end %>
  </div>
</div>

app/views/tools/new.html.erb
<div class="container">
  <h1 class="my-4">New Tool</h1>
  <%= render 'form' %>
</div>

app/views/tools/show.html.erb
<div class="container">
  <div class="my-4">
    <span class="h1 h1-smaller mr-1">
      <%= @tool.name.capitalize %>
    </span>
    <% if policy(@tool).edit? %>
      <%= link_to edit_tool_path(@tool) do %>
        <i class="fas fa-edit mr-1"></i>
      <% end %>
    <% end %>
    <% if policy(@tool).destroy? %>
      <%= link_to tool_path(@tool), method: :delete,
      data: { confirm: "Are you sure you want to delete this tool?" } do %>
        <i class="fas fa-trash mr-1"></i>
      <% end %>
    <% end %>
  </div>

  <div>
    <p><%= @tool.description %></p>
  </div>
  <div>
    <%= link_to new_tool_booking_path(@tool) do %>
      <i class="fas fa-satellite-dish mr-1"></i>
      Book this tool
    <% end %>
  </div>
  <div>
    <%= link_to tools_path do %>
      <i class="fas fa-arrow-left mr-1"></i>
      Back to Tools
    <% end %>
  </div>
</div>